"""empty message

Revision ID: 230009ac7356
Revises: 4febd34fc91e
Create Date: 2017-09-26 11:23:55.814106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230009ac7356'
down_revision = '4febd34fc91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friends_user2_fkey', 'friends', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('friends_user2_fkey', 'friends', 'users', ['user2'], ['id'])
    # ### end Alembic commands ###
